version: 2

project_name: MailView
snapshot:
  version_template: "{{ .Env.MAILVIEW_VERSION }}"
env: [GO111MODULE=on, CGO_ENABLED=0]

before:
  hooks: [make build-frontend]

builds:
  - id: mailview
    binary: mailview
    main: ./cmd
    goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
    goarch: [amd64, arm64, arm]
    goarm: [6, 7]
    ignore:
      - {goos: windows, goarch: arm}
    ldflags:
      - -s -w -X "main.buildString=nightly ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "main.versionString={{ .Env.MAILVIEW_VERSION }}"
    hooks:
      post: make pack-bin BIN={{ .Path }}

archives:
  - id: mailview
    formats: [tar.gz]
    name_template: "MailView_nightly_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    files: [README.md, LICENSE]

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids: [mailview]
    image_templates: ["ghcr.io/jr1machado/mailview:nightly-amd64"]
    build_flag_templates: ["--platform=linux/amd64"]
    dockerfile: Dockerfile.goreleaser
    extra_files: [config.toml.sample, docker-entrypoint.sh]
  - use: buildx
    goos: linux
    goarch: arm64
    ids: [mailview]
    image_templates: ["ghcr.io/jr1machado/mailview:nightly-arm64v8"]
    build_flag_templates: ["--platform=linux/arm64/v8"]
    dockerfile: Dockerfile.goreleaser
    extra_files: [config.toml.sample, docker-entrypoint.sh]
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    ids: [mailview]
    image_templates: ["ghcr.io/jr1machado/mailview:nightly-armv6"]
    build_flag_templates: ["--platform=linux/arm/v6"]
    dockerfile: Dockerfile.goreleaser
    extra_files: [config.toml.sample, docker-entrypoint.sh]
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    ids: [mailview]
    image_templates: ["ghcr.io/jr1machado/mailview:nightly-armv7"]
    build_flag_templates: ["--platform=linux/arm/v7"]
    dockerfile: Dockerfile.goreleaser
    extra_files: [config.toml.sample, docker-entrypoint.sh]

changelog:
  disable: true
checksum:
  name_template: "MailView_nightly_checksums.txt"
